# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/elay/workspace/OpencvTest

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/elay/workspace/OpencvTest

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/elay/workspace/OpencvTest/CMakeFiles /home/elay/workspace/OpencvTest/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/elay/workspace/OpencvTest/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named load

# Build rule for target.
load: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 load
.PHONY : load

# fast build rule for target.
load/fast:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/build
.PHONY : load/fast

EquiTrans.o: EquiTrans.cpp.o
.PHONY : EquiTrans.o

# target to build an object file
EquiTrans.cpp.o:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/EquiTrans.cpp.o
.PHONY : EquiTrans.cpp.o

EquiTrans.i: EquiTrans.cpp.i
.PHONY : EquiTrans.i

# target to preprocess a source file
EquiTrans.cpp.i:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/EquiTrans.cpp.i
.PHONY : EquiTrans.cpp.i

EquiTrans.s: EquiTrans.cpp.s
.PHONY : EquiTrans.s

# target to generate assembly for a file
EquiTrans.cpp.s:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/EquiTrans.cpp.s
.PHONY : EquiTrans.cpp.s

MathCalcs.o: MathCalcs.cpp.o
.PHONY : MathCalcs.o

# target to build an object file
MathCalcs.cpp.o:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/MathCalcs.cpp.o
.PHONY : MathCalcs.cpp.o

MathCalcs.i: MathCalcs.cpp.i
.PHONY : MathCalcs.i

# target to preprocess a source file
MathCalcs.cpp.i:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/MathCalcs.cpp.i
.PHONY : MathCalcs.cpp.i

MathCalcs.s: MathCalcs.cpp.s
.PHONY : MathCalcs.s

# target to generate assembly for a file
MathCalcs.cpp.s:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/MathCalcs.cpp.s
.PHONY : MathCalcs.cpp.s

OcvManip.o: OcvManip.cpp.o
.PHONY : OcvManip.o

# target to build an object file
OcvManip.cpp.o:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/OcvManip.cpp.o
.PHONY : OcvManip.cpp.o

OcvManip.i: OcvManip.cpp.i
.PHONY : OcvManip.i

# target to preprocess a source file
OcvManip.cpp.i:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/OcvManip.cpp.i
.PHONY : OcvManip.cpp.i

OcvManip.s: OcvManip.cpp.s
.PHONY : OcvManip.s

# target to generate assembly for a file
OcvManip.cpp.s:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/OcvManip.cpp.s
.PHONY : OcvManip.cpp.s

PclManip.o: PclManip.cpp.o
.PHONY : PclManip.o

# target to build an object file
PclManip.cpp.o:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/PclManip.cpp.o
.PHONY : PclManip.cpp.o

PclManip.i: PclManip.cpp.i
.PHONY : PclManip.i

# target to preprocess a source file
PclManip.cpp.i:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/PclManip.cpp.i
.PHONY : PclManip.cpp.i

PclManip.s: PclManip.cpp.s
.PHONY : PclManip.s

# target to generate assembly for a file
PclManip.cpp.s:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/PclManip.cpp.s
.PHONY : PclManip.cpp.s

PersCamera.o: PersCamera.cpp.o
.PHONY : PersCamera.o

# target to build an object file
PersCamera.cpp.o:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/PersCamera.cpp.o
.PHONY : PersCamera.cpp.o

PersCamera.i: PersCamera.cpp.i
.PHONY : PersCamera.i

# target to preprocess a source file
PersCamera.cpp.i:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/PersCamera.cpp.i
.PHONY : PersCamera.cpp.i

PersCamera.s: PersCamera.cpp.s
.PHONY : PersCamera.s

# target to generate assembly for a file
PersCamera.cpp.s:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/PersCamera.cpp.s
.PHONY : PersCamera.cpp.s

PointFeature.o: PointFeature.cpp.o
.PHONY : PointFeature.o

# target to build an object file
PointFeature.cpp.o:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/PointFeature.cpp.o
.PHONY : PointFeature.cpp.o

PointFeature.i: PointFeature.cpp.i
.PHONY : PointFeature.i

# target to preprocess a source file
PointFeature.cpp.i:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/PointFeature.cpp.i
.PHONY : PointFeature.cpp.i

PointFeature.s: PointFeature.cpp.s
.PHONY : PointFeature.s

# target to generate assembly for a file
PointFeature.cpp.s:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/PointFeature.cpp.s
.PHONY : PointFeature.cpp.s

Triangle.o: Triangle.cpp.o
.PHONY : Triangle.o

# target to build an object file
Triangle.cpp.o:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/Triangle.cpp.o
.PHONY : Triangle.cpp.o

Triangle.i: Triangle.cpp.i
.PHONY : Triangle.i

# target to preprocess a source file
Triangle.cpp.i:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/Triangle.cpp.i
.PHONY : Triangle.cpp.i

Triangle.s: Triangle.cpp.s
.PHONY : Triangle.s

# target to generate assembly for a file
Triangle.cpp.s:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/Triangle.cpp.s
.PHONY : Triangle.cpp.s

WarpImage.o: WarpImage.cpp.o
.PHONY : WarpImage.o

# target to build an object file
WarpImage.cpp.o:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/WarpImage.cpp.o
.PHONY : WarpImage.cpp.o

WarpImage.i: WarpImage.cpp.i
.PHONY : WarpImage.i

# target to preprocess a source file
WarpImage.cpp.i:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/WarpImage.cpp.i
.PHONY : WarpImage.cpp.i

WarpImage.s: WarpImage.cpp.s
.PHONY : WarpImage.s

# target to generate assembly for a file
WarpImage.cpp.s:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/WarpImage.cpp.s
.PHONY : WarpImage.cpp.s

load.o: load.cpp.o
.PHONY : load.o

# target to build an object file
load.cpp.o:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/load.cpp.o
.PHONY : load.cpp.o

load.i: load.cpp.i
.PHONY : load.i

# target to preprocess a source file
load.cpp.i:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/load.cpp.i
.PHONY : load.cpp.i

load.s: load.cpp.s
.PHONY : load.s

# target to generate assembly for a file
load.cpp.s:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/load.cpp.s
.PHONY : load.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... load"
	@echo "... rebuild_cache"
	@echo "... EquiTrans.o"
	@echo "... EquiTrans.i"
	@echo "... EquiTrans.s"
	@echo "... MathCalcs.o"
	@echo "... MathCalcs.i"
	@echo "... MathCalcs.s"
	@echo "... OcvManip.o"
	@echo "... OcvManip.i"
	@echo "... OcvManip.s"
	@echo "... PclManip.o"
	@echo "... PclManip.i"
	@echo "... PclManip.s"
	@echo "... PersCamera.o"
	@echo "... PersCamera.i"
	@echo "... PersCamera.s"
	@echo "... PointFeature.o"
	@echo "... PointFeature.i"
	@echo "... PointFeature.s"
	@echo "... Triangle.o"
	@echo "... Triangle.i"
	@echo "... Triangle.s"
	@echo "... WarpImage.o"
	@echo "... WarpImage.i"
	@echo "... WarpImage.s"
	@echo "... load.o"
	@echo "... load.i"
	@echo "... load.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

